spring:
  datasource:
    url: jdbc:h2:file:./h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
  h2:
    console.enabled: true

camunda.bpm.admin-user:
  id: demo
  password: demo

grpc:
  server:
    port: 9090
# implemented using configuration. Check class GrpcServerConfigurer
#    security:
#      enabled: true
#      certificate-chain: file:/home/binayak/.keys/server-cert.pem
#      private-key: file:/home/binayak/.keys/server-key.pem
#      trust-cert-collection: file:/home/binayak/.keys/client-cert.pem
#      client-auth: require